set_property IOSTANDARD LVCMOS33 [get_ports {led_o[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_o[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_o[0]}]
set_property PACKAGE_PIN H17 [get_ports {led_o[2]}]
set_property PACKAGE_PIN K15 [get_ports {led_o[1]}]
set_property PACKAGE_PIN J13 [get_ports {led_o[0]}]
